[theme]
primaryColor = "#10b981"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"


[server]
fileWatcherType = "auto"
headless = true
enableCORS = false
enableXsrfProtection = true